### ISSUE TITLE
2x red STOPPED + close script?

### ISSUE THREAD

**Issue by Vlandmist** [sly9/VoyagerTelegramBot#23]
Hi, two quick questions
1) What is the meaning of the red **STOPPED** text, in the script interface? 

![image](https://user-images.githubusercontent.com/6247124/146960351-d211e44a-7f70-4688-99f9-4257e9ec9f88.png)

2) is a there a way to close the bot with a keyboard combination (eg. Ctrl + C)? Or do I just close the cmd window (I'm on Windows)?

**Comment by bigpizza** [comment]
Hi Vlandmist,

1. ***What is the meaning of the red STOPPED text, in the script interface?***
    
    The 2 'STOPPED' text are for 'GUIDING' and 'DITHERING'. All three (including the 'TRACKING') are reported from Voyager's control data.

2. ***is a there a way to close the bot with a keyboard combination (eg. Ctrl + C)? Or do I just close the cmd window (I'm on Windows)?***
    
    We havn't finish the module to accept user's keyborad input, so in general, Ctrl+C or other combination would not work. For the version with tag v0.1.2, directly close the cmd windows is good.

**Comment by Vlandmist** [comment]
ok, great. Maybe it could be considered to replace both texts "stopped" with "guiding" and "dithering". the red color already means OFF.

**Comment by bigpizza** [comment]
The UI is still being tweaked. current version is just a trial how we could use Voyager info as a monitoring system. :D
