### ISSUE TITLE
[Win10] ImportError: No module named '_curses'  (SOLVED)

### ISSUE THREAD

**Issue by Vlandmist** [sly9/VoyagerTelegramBot#24]
Installation of the bot on Windows 10 (with `pip3 install -r requirements.txt`) appears to be ok but as soon as you try to start the bot you get an error msg about missing module `_curses`

I solved it by installing it with `pip install windows-curses`

source: https://stackoverflow.com/questions/35850362/importerror-no-module-named-curses-when-trying-to-import-blessings

**Comment by bigpizza** [comment]
Thanks, Vlandmist. This is the solution.

The dependency was introduced after the latest released version (v0.1.1), and it is a "Windows-only" requirement. Thus we didn't add it to the `requirements.txt`.

Thanks again for pointing it out, we will update the README asap.
